### ISSUE TITLE
.sessionerrors - calamares

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Tint2#2]
tint2 : nb monitor 2, nb monitor used 2, nb desktop 4
Could not open file /usr/share/applications/calamares.desktop

one of the launcher icons that is still in tint2 and not on /usr/share/applications...

**Comment by Dobbie03** [comment]
Is this pre-install or post-install?

**Comment by erikdubois** [comment]
post-install on ssd

**Comment by Dobbie03** [comment]
Did you install using Calamares or ABIF?

**Comment by erikdubois** [comment]
always calamares until now
love it

**Comment by Dobbie03** [comment]
Normally when you use Calamares the install icon disappears upon first boot of installed system.  Normally it was only if you used ABIF that it stuck around.

**Comment by erikdubois** [comment]
if we can the cleanup.sh to work ...

**Comment by erikdubois** [comment]
the icon does not appear because it found no icon for calamares
but the line to show calamares is still in tint2rc!!
that produces these errors since there is no icon

**Comment by erikdubois** [comment]
cleanup.sh script works
no calamares line in tint2rc
