### ISSUE TITLE
standard tint2

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Tint2#3]
if you choose a new tint2 file - do we still have the original tint2 file to go back to

to be investigated!

**Comment by Dobbie03** [comment]
Yes, if you use tint2zen.  If you use the Tint2 Gui then no, it overrides.

**Comment by erikdubois** [comment]
yeah i noticed that now
will add the standard one to /usr...

**Comment by erikdubois** [comment]
is now fixed >4.0.5
